<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    // 我们在JS中使用try catch进行浏览器的异常信息捕获
//    console.log(num); // Uncaught RefereceError: num is not defined 在JS中,本行报错,下面的代码就不再执行了
//    console.log('ok');

    // 以下行代码报错,如果用try/catch捕获了异常信息,不影响下面的代码继续执行;
    // 如果try中的代码执行出错了,会默认的执行catch中的代码
//    try {
//        console.log(num);
//    } catch (e) { // -> 形参必须要写,我们一般起名为e
//        console.log(e.message); // -> num is not defined,可以收集当前代码报错的原因
//        console.log('error');
//    }
//    console.log('ok');

//    try {
//        // JS code
//    } catch (e) {
//        // 如果代码报错,执行catch中的代码
//    } finally {
//        // 一般不用: 不管try中的代码是否报错,都要执行finally中的代码
//    }

    // 有时候既想捕获到错误信息,又想不让下面代码执行
    try {
        console.log(num);
    } catch (e) {
//        console.log(e.message); // -> 可以得到错误的信息,把其进行统计

        // -> 手动抛出一条错误信息,终止代码执行
        throw new Error(e.message);
//        new ReferenceError -> 引用错误
//        new TypeError -> 类型错误
//        new RangeError -> 范围错误
    }
    console.log('ok');

</script>
</body>
</html>